version: "3"

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myprojectuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
    volumes:
      - /var/lib/postgresql/12/main:/var/lib/postgresql/data/
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 30s
      timeout: 30s
      retries: 3
      
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1026:1025 # smtp server
      - 8026:8025 # web ui    


  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - ./adminSystem/adminSystem/.env
    ports:
      - "8001:8000"
    volumes:
      - static_volume:/app/static
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.http.config:/etc/nginx/nginx.conf
      #- ./assets/nginx/certs:/etc/nginx/certs
      - static_volume:/app/static
    ports:
      # - "443:443"
      - "81:80"
    depends_on:
      - django
    restart:
      on-failure:5

volumes:
  dj_postgres_data:
  static_volume:
